### ISSUE TITLE
Is clc-stackage up to date?

### ISSUE THREAD

**Issue by googleson78** [Bodigrim/clc-stackage#14]
I followed the instructions in the readme while trying out a change to `base`, but I got a bunch of failures (after building ghc from the `ghc-9.4` branch) which seem to be entirely unrelated to my change.

Can anyone confirm if they've successfully used `clc-stackage` from c6dda591c826ccacf679d900a820f9840681625c while also using a ghc built from `ghc-9.4`(which is currently `a213d3676550a0e4d542172de539c0cfa2662431`)?

**Comment by tbidne** [comment]
I'm fairly certain there have been successful builds since my changes. At least there have been several accepted clc proposals that passed an impact assessment (e.g. [one](https://github.com/haskell/core-libraries-committee/issues/165), [two](https://github.com/haskell/core-libraries-committee/issues/158), [three](https://github.com/haskell/core-libraries-committee/issues/167)).

I'll try again myself, though I expect the nix issues to resurface. [This issue](https://github.com/haskell/cabal/issues/8824#issuecomment-1509174996) looks like it could be relevant.

Incidentally, it may be a good idea to move to 9.6 as nightly now exceeds lts for number of packages.

**Comment by Bodigrim** [comment]
@tbidne I'd love to migrate to 9.6 fairly soon. I think `crypton{,ite}` universe can use a week or two to catch up on Stackage, but otherwise I'd massively appreciate a PR.

**Comment by konsumlamm** [comment]
> I'm fairly certain there have been successful builds since my changes. At least there have been several accepted clc proposals that passed an impact assessment (e.g. [one](https://github.com/haskell/core-libraries-committee/issues/165), [two](https://github.com/haskell/core-libraries-committee/issues/158), [three](https://github.com/haskell/core-libraries-committee/issues/167)).

Note that while https://github.com/haskell/core-libraries-committee/issues/158 passed impact assessment, the `clc-stackage` build actually failed, see https://github.com/haskell/core-libraries-committee/issues/158#issuecomment-1537226472.

**Comment by mixphix** [comment]
It's kind of difficult to run impact assessments for proposals when this library is not kept in sync with the latest compiler version (off of which new MRs will need to branch).

**Comment by Bodigrim** [comment]
@mixphix sorry, I've been slow recently. I hope to land #16 soon.

**Comment by Bodigrim** [comment]
Thanks to @tbidne, it is up-to-date now.
